apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ajudadorabot-staging

namespace: ajudadorabot-staging

resources:
- ../base/namespace.yaml
- ../base/configmap.yaml
- ../base/deployment.yaml
- ../base/service.yaml
- ../base/ingress.yaml
- ../base/pvc.yaml
- ../base/rbac.yaml
- ../base/hpa.yaml
- secrets.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml

images:
- name: ghcr.io/yourusername/ajudadorabot
  newTag: staging

commonLabels:
  environment: staging
  app.kubernetes.io/instance: ajudadorabot-staging

configMapGenerator:
- name: ajudadorabot-config-staging
  files:
  - appsettings.staging.json
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: ajudadorabot-secrets-staging
  envs:
  - .env.staging
  options:
    disableNameSuffixHash: true

replicas:
- name: ajudadorabot-api
  count: 1
- name: ajudadorabot-nginx
  count: 1