apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ajudadorabot-api-pdb
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ajudadorabot
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ajudadorabot-nginx-pdb
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: nginx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ajudadorabot
      app.kubernetes.io/component: nginx