apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ajudadorabot-data-pvc
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ajudadorabot-backup-pvc
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard