apiVersion: v1
kind: ServiceAccount
metadata:
  name: ajudadorabot-api
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: api
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ajudadorabot-api
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: api
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ajudadorabot-api
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: api
subjects:
- kind: ServiceAccount
  name: ajudadorabot-api
  namespace: default
roleRef:
  kind: Role
  name: ajudadorabot-api
  apiGroup: rbac.authorization.k8s.io