# Kubernetes Secrets Template
# This file contains templates for secrets - actual values should be managed via external secret management
apiVersion: v1
kind: Secret
metadata:
  name: ajudadorabot-secrets
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Telegram Bot Configuration
  telegram-bot-token: ""  # Set via external secret management
  webhook-url: ""         # Set via external secret management
  webhook-secret-token: "" # Set via external secret management
  
  # JWT Configuration  
  jwt-secret: ""          # Set via external secret management
  jwt-issuer: "AjudadoraBot"
  jwt-audience: "AjudadoraBot-Users"
  
  # Database Configuration
  database-connection-string: "Data Source=/app/data/ajudadorabot.db"
  postgres-connection-string: ""  # Set via external secret management
  
  # Redis Configuration
  redis-connection-string: ""     # Set via external secret management
  redis-password: ""              # Set via external secret management
  
  # External Services
  smtp-username: ""               # Set via external secret management
  smtp-password: ""               # Set via external secret management
  
  # Monitoring & Alerting
  grafana-admin-password: ""      # Set via external secret management
  slack-webhook-url: ""           # Set via external secret management
  discord-webhook-url: ""         # Set via external secret management
  
  # Cloud Storage
  aws-access-key-id: ""           # Set via external secret management
  aws-secret-access-key: ""       # Set via external secret management
  
  # Encryption
  encryption-key: ""              # Set via external secret management
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: ""  # Base64 encoded certificate - Set via cert-manager
  tls.key: ""  # Base64 encoded private key - Set via cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  labels:
    app.kubernetes.io/name: ajudadorabot
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""  # Base64 encoded Docker registry credentials